### ISSUE TITLE
[[stitchable]] approach?

### ISSUE THREAD

**Issue by alex-spinsight** [63rabbits/CI_ColorKernelSample#1]
Did you try the approach discussed in https://developer.apple.com/wwdc21/10159 ? I can not get it to work as adding "-framework CoreImage" gives me air error framework not found. Was wondering if you had similar issues

**Comment by 63rabbits** [comment]
I tried it and had the same problem.
I searched Google and found the following hits.
https://developer.apple.com/forums/thread/687564

I removed the "-framework CoreImage" flag and ran the following kernel and it worked.

```
#include <CoreImage/CoreImage.h>
using namespace metal;

[[stitchable]] float4 colorShift(coreimage::sample_t s) {
    return s.gbra;
}
```

Don't forget. : Build Settings > Metal Compiler - Build Options > Ohter Metal Compiler Flags : -fcikernel

**Comment by 63rabbits** [comment]
Removing the following flags still works. Why?

Build Settings > Metal Compiler - Build Options > Ohter Metal Compiler Flags : -fcikernel

**Comment by alex-spinsight** [comment]
As I understand fckernel is not required with stitchable , only required flag is -framework CoreImage

**Comment by 63rabbits** [comment]
Summarize below and close this issue.

- Option specification when using CIColorKernel, CIWarpKenel, CIBlendKernel, or CIKernel.
  - Ohter Metal Compiler Flags : -fcikernel
  - Ohter Metal Linker Flags : -fcikernel

- Option to use [[stitchable]] for the Metal Shading program.
  - Ohter Metal Compiler Flags : -fcikernel <-- can be either.
  - Ohter Metal Linker Flags : -fcikernel <-- Remove.



```
#include <CoreImage/CoreImage.h>

extern "C" {
    namespace coreimage {

        [[stitchable]] float4 colorShift(sample_t s) {
            return s.gbra;
        }

    }
}
```

or

```
#include <CoreImage/CoreImage.h>
using namespace metal;

[[stitchable]] float4 colorShift(coreimage::sample_t s) {
    return s.gbra;
}
```
